<a href="https://colab.research.google.com/github/dgiridaran/Learning_pytorch/blob/main/pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.4.1+cu121'

In [3]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Check number of dimensions
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# tensor
TENSOR = torch.tensor([[[1,2],
                       [3,6],
                       [2,4]]])


In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 2])

- scaler single number 0 dim
- vector 1 dim
- MATRIX 2 dim
- TENSOR n dim

## Creating a Tensor random numbers (parameters in ML algoritham)

In [15]:
# create a random tensor size (3, 4)
random_tensor = torch.rand(size=(3,4))

In [16]:
random_tensor

tensor([[0.8445, 0.8862, 0.2076, 0.2699],
        [0.9525, 0.5579, 0.8244, 0.6148],
        [0.6163, 0.5999, 0.9956, 0.9306]])

In [17]:
random_tensor.dtype

torch.float32

The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [18]:
# create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

In [19]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [20]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)


Creating a range and tensors like

In [21]:
zero_to_ten = torch.range(0,10,2)  # this is depricated
zero_to_ten

<ipython-input-21-79abb246a814>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(0,10,2)  # this is depricated


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [22]:
zero_to_ten = torch.arange(start=0,end=10,step=1) # so use this
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

In [23]:
torch.zeros_like(input=zero_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
# Default datatype for tensor is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                 dtype = None, # defaults to None, which is torch.float32 or whatever datatype is passed
                                 device=None, # defaults to None, which uses the default tensor type
                                 requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [25]:
float_32_tensor

tensor([3., 6., 9.])


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

- For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

- Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

In [26]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                                 dtype = torch.float16)
float_16_tensor.dtype

torch.float16

## Getting information from tensors

In [27]:
some_tensor = torch.rand(3,4)

print(some_tensor)

tensor([[0.5498, 0.1107, 0.0116, 0.2405],
        [0.5917, 0.3895, 0.5443, 0.1465],
        [0.7260, 0.7001, 0.1505, 0.7003]])


In [28]:
some_tensor.shape

torch.Size([3, 4])

In [29]:
some_tensor.dtype

torch.float32

In [30]:
# Device tensor is stored in CPU

some_tensor.device

device(type='cpu')

## Basic operations

In [31]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [34]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [35]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [36]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)

print(tensor, "*" ,tensor)
print("Equals", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


## Matrix multiplication (is all you need)

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work
The resulting matrix has the shape of the outer dimensions:
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)

In [39]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Operation	Calculation	Code
Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor
Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

In [40]:
# Element wise matrix multiplication

tensor * tensor

tensor([1, 4, 9])

In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

## One of the most common errors in deep learning (shape errors)

In [43]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [44]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [45]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [46]:
output = torch.matmul(tensor_A , tensor_B.T)
output

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [47]:
# torch.mm is a shortcut for matmul

torch.mm(tensor_A , tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Creating a Linear layer

In [48]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3, out_features=6)

x = tensor_A.T
print(x)
output = linear(x)

print(x.shape)

print(output)

tensor([[1., 3., 5.],
        [2., 4., 6.]])
torch.Size([2, 3])
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)


In [49]:
print(linear)

Linear(in_features=3, out_features=6, bias=True)


In [50]:
tensor_A = torch.tensor([1,
                         3,
                         5], dtype=torch.float32)

In [51]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3, out_features=6)

x = tensor_A.T
print(x)
output = linear(x)

print(x.shape)

print(output)

tensor([1., 3., 5.])
torch.Size([3])
tensor([0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
       grad_fn=<ViewBackward0>)


<ipython-input-51-a98686d1ea78>:5: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3697.)
  x = tensor_A.T


## Finding the min, max, mean, sum, etc (aggregation)

In [52]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
x.min()

tensor(0)

In [54]:

x.max()

tensor(90)

In [55]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

You may find some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.

In [56]:
x.type(torch.float32).mean()

tensor(45.)

In [57]:
x.sum()

tensor(450)

## Positional min/max

In [58]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])


In [59]:
tensor.argmax()

tensor(8)

In [60]:
tensor.argmin()

tensor(0)

## Change tensor datatype


As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in torch.float64 and another is in torch.float32, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype you'd like to use.

In [61]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [62]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [63]:
# create a float8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

Note: Different datatypes can be confusing to begin with. But think of it like this, the lower the number (e.g. 32, 16, 8), the less precise a computer stores the value. And with a lower amount of storage, this generally results in faster computation and a smaller overall model. Mobile-based neural networks often operate with 8-bit integers, smaller and faster to run but less accurate than their float32 counterparts.

## Reshaping, stacking, squeezing and unsqueezing

In [64]:
x = torch.arange(1., 8.)
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [65]:
# add extra dimensions

x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [66]:
# Change view (keeps same data as original but changes view)
z = x.view(1,7)
z

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [67]:
x.fill_(9)

tensor([9., 9., 9., 9., 9., 9., 9.])

In [68]:
z

tensor([[9., 9., 9., 9., 9., 9., 9.]])

In [69]:
x_reshaped

tensor([[9., 9., 9., 9., 9., 9., 9.]])

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.


In [70]:
z[:, 5] = 10

In [71]:
z

tensor([[ 9.,  9.,  9.,  9.,  9., 10.,  9.]])

In [72]:
x

tensor([ 9.,  9.,  9.,  9.,  9., 10.,  9.])

If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().

In [73]:
# stack tensor on top of each other

x_stacked = torch.stack([x, x, x, x, x], dim=1)
x_stacked

tensor([[ 9.,  9.,  9.,  9.,  9.],
        [ 9.,  9.,  9.,  9.,  9.],
        [ 9.,  9.,  9.,  9.,  9.],
        [ 9.,  9.,  9.,  9.,  9.],
        [ 9.,  9.,  9.,  9.,  9.],
        [10., 10., 10., 10., 10.],
        [ 9.,  9.,  9.,  9.,  9.]])

ow about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()` (I remember this as squeezing the tensor to only have dimensions over 1).

In [74]:
print(f"previous tensor : {x_reshaped}")
print(f"shape: {x_reshaped.shape}")

previous tensor : tensor([[ 9.,  9.,  9.,  9.,  9., 10.,  9.]])
shape: torch.Size([1, 7])


In [75]:
x_squeezed = x_reshaped.squeeze()
print(f"squeezed tensor: {x_squeezed}")
print(f"shape: {x_squeezed.shape}")

squeezed tensor: tensor([ 9.,  9.,  9.,  9.,  9., 10.,  9.])
shape: torch.Size([7])


And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [76]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

In [77]:
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 9.,  9.,  9.,  9.,  9., 10.,  9.]]), torch.Size([1, 7]))

You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [78]:
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1)   # shifts axis 0->1, 1->2, 2->0

print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

In [79]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [80]:
# Let's index bracket by bracket

print(x[0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [81]:
print(x[0][0])

tensor([1, 2, 3])


In [82]:
print(x[0][0][0])

tensor(1)


In [83]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [84]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [85]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [86]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

- `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
- `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [87]:
import numpy as np

In [88]:
array = np.arange(1., 8.)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [89]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [90]:
array

array([1., 2., 3., 4., 5., 6., 7.])

In [91]:
# Tensor to NumPy array

tensor = torch.ones(7)

numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the ! (also called bang) means "run this on the command line".



In [92]:
!nvidia-smi

Fri Oct  4 17:41:45 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

You can test if PyTorch has access to a GPU using `torch.cuda.is_available()`

In [93]:
torch.cuda.is_available()

True

In [94]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

You can count the number of GPUs PyTorch has access to using `torch.cuda.device_count()`.

In [95]:
torch.cuda.device_count()

1

 Putting a tensor on GPU using to(device) (e.g. `some_tensor.to(device)`) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:

some_tensor = some_tensor.to(device)

In [96]:
# Create a tensor default on GPU
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu1 = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)
print(tensor_on_gpu1, tensor_on_gpu1.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0
tensor([1, 2, 3], device='cuda:0') cuda:0


Notice the second tensor has device='cuda:0', this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be 'cuda:0' and 'cuda:1' respectively, up to 'cuda:n').

In [97]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

In [98]:
tensor_back_on_CPU = tensor_on_gpu.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3])

In [99]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')