<a href="https://colab.research.google.com/github/dgiridaran/Learning_pytorch/blob/main/pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.4.1+cu121'

In [3]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Check number of dimensions
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# tensor
TENSOR = torch.tensor([[[1,2],
                       [3,6],
                       [2,4]]])


In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 2])

- scaler single number 0 dim
- vector 1 dim
- MATRIX 2 dim
- TENSOR n dim

## Creating a Tensor random numbers (parameters in ML algoritham)

In [15]:
# create a random tensor size (3, 4)
random_tensor = torch.rand(size=(3,4))

In [16]:
random_tensor

tensor([[0.0557, 0.7939, 0.2298, 0.3637],
        [0.8413, 0.6868, 0.0995, 0.1848],
        [0.0847, 0.5248, 0.4695, 0.4341]])

In [17]:
random_tensor.dtype

torch.float32

The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [18]:
# create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

In [19]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [20]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)


Creating a range and tensors like

In [21]:
zero_to_ten = torch.range(0,10,2)  # this is depricated
zero_to_ten

<ipython-input-21-79abb246a814>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(0,10,2)  # this is depricated


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [22]:
zero_to_ten = torch.arange(start=0,end=10,step=1) # so use this
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

In [23]:
torch.zeros_like(input=zero_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
# Default datatype for tensor is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                 dtype = None, # defaults to None, which is torch.float32 or whatever datatype is passed
                                 device=None, # defaults to None, which uses the default tensor type
                                 requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [25]:
float_32_tensor

tensor([3., 6., 9.])


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

- For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

- Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

In [26]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                                 dtype = torch.float16)
float_16_tensor.dtype

torch.float16

## Getting information from tensors

In [27]:
some_tensor = torch.rand(3,4)

print(some_tensor)

tensor([[0.0695, 0.6605, 0.9631, 0.5178],
        [0.4571, 0.2242, 0.8280, 0.1255],
        [0.4062, 0.8360, 0.2463, 0.3282]])


In [28]:
some_tensor.shape

torch.Size([3, 4])

In [29]:
some_tensor.dtype

torch.float32

In [30]:
# Device tensor is stored in CPU

some_tensor.device

device(type='cpu')

## Basic operations

In [31]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [34]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [35]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [36]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)

print(tensor, "*" ,tensor)
print("Equals", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


## Matrix multiplication (is all you need)

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work
The resulting matrix has the shape of the outer dimensions:
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)

In [39]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Operation	Calculation	Code
Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor
Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

In [40]:
# Element wise matrix multiplication

tensor * tensor

tensor([1, 4, 9])

In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

## One of the most common errors in deep learning (shape errors)

In [43]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [44]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [45]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [46]:
output = torch.matmul(tensor_A , tensor_B.T)
output

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [47]:
# torch.mm is a shortcut for matmul

torch.mm(tensor_A , tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Creating a Linear layer

In [48]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3, out_features=6)

x = tensor_A.T
print(x)
output = linear(x)

print(x.shape)

print(output)

tensor([[1., 3., 5.],
        [2., 4., 6.]])
torch.Size([2, 3])
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)


In [49]:
print(linear)

Linear(in_features=3, out_features=6, bias=True)


In [50]:
tensor_A = torch.tensor([1,
                         3,
                         5], dtype=torch.float32)

In [51]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3, out_features=6)

x = tensor_A.T
print(x)
output = linear(x)

print(x.shape)

print(output)

tensor([1., 3., 5.])
torch.Size([3])
tensor([0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
       grad_fn=<ViewBackward0>)


<ipython-input-51-a98686d1ea78>:5: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3697.)
  x = tensor_A.T


## Finding the min, max, mean, sum, etc (aggregation)

In [53]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
x.min()

tensor(0)

In [57]:

x.max()

tensor(90)

In [63]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

You may find some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.

In [61]:
x.type(torch.float32).mean()

tensor(45.)

In [62]:
x.sum()

tensor(450)

## Positional min/max

In [64]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])


In [65]:
tensor.argmax()

tensor(8)

In [66]:
tensor.argmin()

tensor(0)

## Change tensor datatype


As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in torch.float64 and another is in torch.float32, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype you'd like to use.

In [70]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [73]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [76]:
# create a float8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)