<a href="https://colab.research.google.com/github/dgiridaran/Learning_pytorch/blob/main/pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
torch.__version__

'2.4.1+cu121'

In [4]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [7]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# Check number of dimensions
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
# tensor
TENSOR = torch.tensor([[[1,2],
                       [3,6],
                       [2,4]]])


In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 2])

- scaler single number 0 dim
- vector 1 dim
- MATRIX 2 dim
- TENSOR n dim

## Creating a Tensor random numbers (parameters in ML algoritham)

In [23]:
# create a random tensor size (3, 4)
random_tensor = torch.rand(size=(3,4))

In [24]:
random_tensor

tensor([[0.5126, 0.8852, 0.2974, 0.2533],
        [0.7893, 0.1811, 0.0482, 0.7483],
        [0.5188, 0.1402, 0.2238, 0.0810]])

In [26]:
random_tensor.dtype

torch.float32

The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [28]:
# create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

In [31]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [32]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)


Creating a range and tensors like

In [39]:
zero_to_ten = torch.range(0,10,2)  # this is depricated
zero_to_ten

<ipython-input-39-79abb246a814>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(0,10,2)  # this is depricated


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [40]:
zero_to_ten = torch.arange(start=0,end=10,step=1) # so use this
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

In [41]:
torch.zeros_like(input=zero_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
# Default datatype for tensor is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                 dtype = None, # defaults to None, which is torch.float32 or whatever datatype is passed
                                 device=None, # defaults to None, which uses the default tensor type
                                 requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [49]:
float_32_tensor

tensor([3., 6., 9.])


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

- For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

- Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

In [51]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                                 dtype = torch.float16)
float_16_tensor.dtype

torch.float16

## Getting information from tensors

In [52]:
some_tensor = torch.rand(3,4)

print(some_tensor)

tensor([[0.3309, 0.7408, 0.1834, 0.1655],
        [0.3583, 0.4426, 0.4733, 0.9064],
        [0.8956, 0.2379, 0.3214, 0.9461]])


In [53]:
some_tensor.shape

torch.Size([3, 4])

In [55]:
some_tensor.dtype

torch.float32

In [57]:
# Device tensor is stored in CPU

some_tensor.device

device(type='cpu')

## Basic operations

In [64]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [65]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [66]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [67]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [68]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [69]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [70]:
tensor

tensor([1, 2, 3])

In [73]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)

print(tensor, "*" ,tensor)
print("Equals", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])
